url:
baseurl:

# Site settings
title: Schoolbag
email: info@schoolbag.ie
description: "Learning Data is a subsidiary of The Examcraft Group and has been providing products which support student learning to Irish schools for over 25 years."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fb8306
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Philip O'Callaghan
  pic: 1
  position: Managing Director

- name: Stuart Johnson
  pic: 2
  position: Technical Director

- name: Amanda Ferris
  pic: 3
  position: Lead Marketer

- name: Sidimar Gobbo
  pic: 4
  position: UX / UI Designer
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: google-plus
  #     url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Schoolbag4HW
  - title: facebook
    url: https://www.facebook.com/learningdata
  - title: google-plus
    url: https://plus.google.com/+LearningdataIe
  - title: vimeo
    url: https://vimeo.com/channels/715348

# Postal address (add as many lines as necessary)
address:
  - line: The Guinness Enterprise Centre, Taylor’s Lane
  - line: Dublin 8, Ireland

# Build settings
markdown: kramdown
permalink: pretty
