url:
baseurl:

# Site settings
title: St. Pauls Primary School
email: info@school.ie
description: "Empowering children to take an active role in society and in the stewardship of the environment."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fb8306
  secondary: f47920
  secondary-dark: 333

# Staff names, titles and social links
people:
  - name: Philip O'Callaghan
    pic: 1
    position: Managing Director
    about: Philip taught for 10 years in Naas CBS and St. David’s CBS, Artane. Since leaving the classroom he has been the managing director of Examcraft, the parent company of Schoolbag.

  - name: Stuart Johnson
    pic: 2
    position: Technical Director
    about: Stuart holds a PhD in Physics from the University of Edinburgh. After gaining his PGCE teaching qualification, he taught first in the UK state system and then in a British school in Spain. He has over 10 years experience building software which helps schools.

  - name: Amanda Ferris
    pic: 3
    position: Digital Education Product Specialist
    about: Amanda is a trained primary and secondary school teacher with a passion for educational technology, she provides support and training to our schools and teachers, and is in charge of product testing.

  - name: Sidimar Gobbo
    pic: 4
    position: UX/UI Designer
    about: Sidimar is a self-taught UX/UI Designer with a passion for design and technology, he provides the design and digital experience for Schoolbag.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Schoolbag4HW
  - title: facebook
    url: https://www.facebook.com/learningdata
  - title: google-plus
    url: https://plus.google.com/+LearningdataIe
  - title: vimeo
    url: https://vimeo.com/channels/715348

# Postal address (add as many lines as necessary)
address:
  - line: The Guinness Enterprise Centre,
  - line:  Taylor’s Lane - Dublin 8, Ireland

# Build settings
markdown: kramdown
permalink: pretty

# jekyll-press:
#   exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
#   js_options: {}      # js minifier options
#   css_options: {}     # css minifier options
#   html_options: {}    # html minifier options
