url:
baseurl: /welcome

# Site settings
title: TYP - My Learning Journey
email: typ@4schools.ie
description: "4schools.ie is a trading name of The Examcraft Group which has been providing products which support student learning to Irish schools for over 25 years."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 559DB2
  secondary: 559DB2
  secondary-dark: 333333

# What our schools have to say
# quotes:
#   - text: It helps me be organised for my homework and keeps me on track. I use it every night to know what I have for homework
#     author: Student


# Team names, titles and social links
# people:
#   - name: Philip O'Callaghan
#     pic: 1
#     position: Managing Director
#     about: Philip taught for 10 years in Naas CBS and St. David’s CBS, Artane. Since leaving the classroom he has been the managing director of Examcraft.
#
#   - name: Stuart Johnson
#     pic: 2
#     position: Technical Director
#     about: Stuart holds a PhD in Physics from the University of Edinburgh. After gaining his PGCE teaching qualification, he taught first in the UK state system and then in a British school in Spain. He has over 10 years experience building software which helps schools.
#
#   - name: Sidimar Gobbo
#     pic: 4
#     position: UX/UI Designer
#     about: Sidimar is a self-taught UX/UI Designer with a passion for design and technology, he provides the design and digital experience for TYP.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/4SchoolsIE
  - title: facebook
    url: https://www.facebook.com/4Schools.ie
  - title: vimeo
    url: https://vimeo.com/theexamcraftgroup

# Postal address (add as many lines as necessary)
address:
  - line: 35 Finglas Business Park, Tolka Valley Road,
  - line: Finglas, Dublin 11, Ireland, D11 YF40

# Build settings
markdown: kramdown
permalink: pretty

# jekyll-press:
#   exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
#   js_options: {}      # js minifier options
#   css_options: {}     # css minifier options
#   html_options: {}    # html minifier options
